TARGET := unianm
CFILES := unianm.c ../../shared/util.c
HFILES := unianm.h ../../shared/cbytesex.h ../../shared/util.h
CPPFLAGS := `pkg-config --cflags libpng`
LDFLAGS := `pkg-config --libs libpng`
DEBUG := 1
#ERROR := 1

include ../../shared/Makefile.default

