TARGET := decomp
CFILES := ../../shared/util.c huff.c decomp.c lztfb.c
HFILES := ../../shared/cbytesex.h ../../shared/util.h dostypes.h huff.h lztfb.h getbit.h
CFLAGS := -std=c99
DEBUG := 1
#ERROR := 1

include ../../shared/Makefile.default

